### ISSUE TITLE
Streaming Meetings to Youtube

### ISSUE THREAD

**Issue by F3n67u** [tc39/notes#201]
How about record our meeting and put it to YouTube after our meeting like Node.js does? Live streaming or not is not relevant.

IMHO. I think the video is more approachable than long paragraph of notes and it is a very good material for learning how tc39 works. 

I personally would prefer video to text note. Long paragraph of text note is hard for me to read and I cannot associated note with the flow of pdf presentation. I missed last meeting on 8x8. I really hope the meeting video recording will exist.

Node.js youtube channel: https://www.youtube.com/c/nodejs-foundation/videos 
Nodejs tsc repo's streaming doc: https://github.com/nodejs/TSC/blob/main/Streaming/Streaming-To-Youtube.md

**Comment by ljharb** [comment]
This is not something the committee as a whole would find acceptable; the notes published on a delay after editing are the most i suspect folks would be comfortable with. Only delegates and invited experts are able to participate (contribute or view) in the meeting directly, by design.

**Comment by ecmageneva** [comment]
Jordan and all. In my opinion the capturing the TC39 meeting on video and sharing it TC39 internally is also a much better practice what we do today, with a lot of pain during the meetings, and the 2 weeks afterward editing. For the current meeting I have already done my part - took me about 2 hours, because my English is not the highest quality... - and it is still not in a best quality to be honest...but I think for the purpose it is good enough. Native speakers have a real advantage that their speech is turned into text with a much better quality. But I observe that many TC39 folks - who should do that editing too - do not do that. No time or too much of a trouble etc. I do not know. The notes are long usually around 150 pages or sometimes even more. I have not made statistics how much of that is actually edited after the 2 weeks. 
I think the committee "as a whole" is not unanimously on the view that sharing such video would be not acceptable, but definitely there are several members who are on such view. Therefore, it would be good to know the concrete reasons of those who have concerns what the concrete concerns are. My feeling is that we are still following a practice that was accepted by some standards bodies but back in the XX century when multimedia capturing of entire standards meetings was not yet supported by the technology. 
The standardization process as such is a process driven by consensus forming. To learn from mistakes, to be influenced during the standardization process, change the opinion, etc. is normal. What counts is the final vote on the finished and published specification up for voting.

**Comment by ljharb** [comment]
@ecmageneva i think the plenary or the reflector is the place to discuss these privacy concerns, as well as to discuss the existing attempts to improve the quality of the notes, not here in a response to the community.

We've also discussed them many times, and this is very much not just a legacy practice, but a current privacy requirement.

**Comment by F3n67u** [comment]
> @ecmageneva i think the plenary or the reflector is the place to discuss these privacy concerns, as well as to discuss the existing attempts to improve the quality of the notes, not here in a response to the community.
> 
> We've also discussed them many times, and this is very much not just a legacy practice, but a current privacy requirement.

@ljharb Thanks for the info. Could you help me understand what privacy requirements stop tc39 from capturing the TC39 meeting on video?

**Comment by ljharb** [comment]
@F3n67u nonzero delegates do not wish their voice and likeness from plenary to be publicly broadcast; it needs no other defense than that.

**Comment by littledan** [comment]
For what it's worth, I'd prefer to move to a model of streaming meetings to whoever is interested in hearing what is going on. I think these meetings are already taking place in public in the normal sense of the word (so there is no reasonable expectation of privacy), and improving accessibility of our deliberations would be positive for our work. However I agree that publicly streamed meetings would be a big decision for the committee to make, and it would require more discussion among committee delegates, which would need to take place internal to the committee, rather than in this repository.
